title: "Fantail GIS"
description: "Maps, Projects, and Visual Work"
author: "Matt Sims"
baseurl: "/portfolio"   
url: "https://matts-maps.github.io"

markdown: kramdown
theme: minima
paginate:          5
paginate_path:     "/posts/page:num/"

include:
  - assets

collections:
  projects:
    output: true


